[versions]
managed-graphql-java = "18.1"
managed-graphql-java-extended-scalars = "18.0"
managed-graphql-java-tools = "12.0.2"
managed-graphql-spqr = "0.11.2"

[libraries]
managed-graphql-java = { module = 'com.graphql-java:graphql-java', version.ref = 'managed-graphql-java' }
managed-graphql-java-extended-scalars = { module = 'com.graphql-java:graphql-java-extended-scalars', version.ref = 'managed-graphql-java-extended-scalars' }
managed-graphql-java-tools = { module = 'com.graphql-java-kickstart:graphql-java-tools', version.ref = 'managed-graphql-java-tools' }
managed-graphql-spqr = { module = 'io.leangen.graphql:spqr', version.ref = 'managed-graphql-spqr' }

reactor-core = { module = 'io.projectreactor:reactor-core' }
